AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  writeondb

  Sample SAM Template for writeondb
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  DbWriteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dbWrite/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref UsersTable
      Events:
        DbWrite:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /write
            Method: post
            ContentType: application/json
            RequestModel:
              ModelName: InserRequestModel
              RestaApiId:
                Ref: ServerlessRestApi

  InsertRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId:
        Ref: ServerlessRestApi
      ContentType: application/json
      Name: InsertRequestModel
      Schema:
        $schema: http://json-schema.org/draft-04/schema#
        title: InsertRequestSchema
        type: object
        properties:
          userId:
            type: string
          name:
            type: string
          surname:
            type: string
        require:
          - itemId
          - name
          - surname

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
        -
          AttributeName: name
          AttributeType: S
        -
          AttributeName: surname
          AttributeType: S
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DbWriteApi:
    Description: "API Gateway endpoint URL for writing on the table"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/write/"
  DbWriteFunction:
    Description: "Function ARN"
    Value: !GetAtt DbWriteFunction.Arn
  DbWriteFunctionFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt DbWriteFunctionRole.Arn
